### ISSUE TITLE
Develop Auth Middleware

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash-realworld-example-app#2]
More enforces a realworld app.

This should check if the user is authed (yet to be implemented how of this works). If not then redirects to login resource

**Related Files**
* /src/middlewares/auth_middleware.ts
* /src/resources/home_resource.ts (for adding the middleware)

**Comment by ebebbington** [comment]
@crookse this can be closed right as the auth is handled within Vue? (as of https://github.com/drashland/deno-drash-realworld-example-app/issues/19)

**Comment by crookse** [comment]
I'm not sure yet. I'm working on the login and register parts of the codebase right now and I'll look into seeing if we need this middleware.

**Comment by crookse** [comment]
This can be closed. Auth is handled and middleware is not needed. By the realworld API spec, we check if the user has a session at the /users/login resource. That's all implemented now.
