### ISSUE TITLE
Split Server and API into Separate Containers?

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash-realworld-example-app#25]
Looking for feedback from @crookse and @Guergeiro 

Should we seperate the API logic & files from the main server?

Eg we could have a file structure like:

```
/.docker/
  src/
    api/
      resources/
        article_resource.ts
      ...
    server|client/
      resources/
        home_resource.ts
      ..
```

This would help in understand the resources, as we might have to have the api resources named like `api_article_resource.ts` and also make the file structrue more readable maybe? Curious what you guys think

**Comment by Guergeiro** [comment]
In my opinion, everyone should aim for micro services, which if people wanted to implement a real app, they should separate everything. Imagine, a container running an API, another container running the web app. Essentially, two Drash instances.

As far as this real world example app, I don't mind if it's everything in the same. It's just an example after all. If we organize de files correctly, I believe the user will be able to understand from where they can extract stuff.

**Comment by ebebbington** [comment]
Ahhh yeah cause it's docker it would be two seperate containers... forgot about that :P I agree though
