### ISSUE TITLE
docker - move deno to /usr/bin

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash-realworld-example-app#63]
<img width="825" alt="Screen Shot 2020-06-23 at 20 58 11" src="https://user-images.githubusercontent.com/12766301/85484292-89ce3000-b594-11ea-8ab9-6f32a2ebe6d3.png">

**Comment by ebebbington** [comment]
Can't harm anything, i'm not fussed so i'm cool with it (and i assume @Guergeiro  is too :P)

**Comment by crookse** [comment]
i just figured we could merge the code in and move this question into an issue so as not to block the merge

**Comment by Guergeiro** [comment]
I prefer to move it there anyways 🤪

**Comment by ebebbington** [comment]
Lets just move it there then?:P It'll take 10 seconds to do anyways :P
