### ISSUE TITLE
Add tag on pressing comma

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash-realworld-example-app#84]
## Summary

What: It would be nice to have tags added when pressing comma in addition to pressing enter when creating/editing an article.

Why: Currently, we have to press enter and a lot of apps have an event on the comma key--allowing for tags to be added using the comma. For example, "hello, test, test, what, the, what" would add 6 tags with each tag being added after pressing comma.

## Acceptance Criteria

- [ ] A tag is added after pressing comma in addition to pressing enter

**Comment by ebebbington** [comment]
How would the input field act after this? So, on pressing comma, would the previous tag be added to the tag list? And if so, would the input field clear itself?

Like as soon as you press `,`, the tag list is updated

**Comment by crookse** [comment]
I think on pressing comma, the previous tag should be added, but that seems like it'd be more work and wouldn't really fit with our UI. I say that because on other sites, as soon as you press comma, the previous tag turns into a pill-looking button, but you can still backspace and delete the entire pill. Our UI isn't set up like that

**Comment by ebebbington** [comment]
Yeah i know what kind of design you mean - maybe we could make that ourselves? 

Regardless, i can start on this issue

**Comment by ebebbington** [comment]
Got this in a working state atm, so how it works is:

1. You type your tag, eg: `[ web dev ]`
2. You press the comma eg: `[ web dev, ]`
3. The tag (`web dev`) is added to the tag list, and displays in the tag list eg: `(x web dev )`
4. The tag input field is 'emptied': `[ ]`

I'll see if i can play around on getting our UI set up to have 'pill looking' tags **inside** the tag input field
