### ISSUE TITLE
Refresh on Home Page Removes New Article Header Item

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash-realworld-example-app#90]
**Describe the bug**
On the home page, if you refresh, the "New Article" item in the header will disappear

**To Reproduce**

1. Go to the home page
2. Refresh your browser
3. See "New Article" item in header has disappeared

**Expected behavior**
It should still stay, you have to click on an article currently for the header to show again, to then create a new article

**Suggested Solution(s)**
Assuming the item display is dependent on something, and the context is lost on a refresh, maybe it's dependent on articles being set?

**Comment by ebebbington** [comment]
It's because after a refresh, the `is_authenticated` returns false, even when signed in

**Comment by ebebbington** [comment]
And thats because we dont check if user is authed onn / :

```
  if (to.path !== "/login" && to.path !== "/register" && to.path !== "/") {
    checkIfUserIsAuthenticated()
  }
```
The reason for the above is cause users can still checkout the home page but not nned to be logged in to do basic stuff like viewing

**Comment by ebebbington** [comment]
@crookse how would we go about this? We'd want to check if the user is authed on `/`, **but dont error** if they aren't, else do error for ay other page, which is pretty much that auth method, but without any of the `routes.push('/login')` stuff

**Comment by tiagostutz** [comment]
Hi @ebebbington I just put the project to run on my machine. Can a beginner like me tackle this?

**Comment by ebebbington** [comment]
Hey @tiagostutz, i guess it depends on your knowledge of Vue, to be honest i am really a beginner and only used it for this project to help out slightly (@crookse did 99% of thee work)

I guess familiarise yourself with the flow, but i think it's an easy issue to tackle - any questions then feel free to ask!

**Comment by tiagostutz** [comment]
Well, to be honest I'm pretty newbie on Vue too.... I'll work on this while learning a bit more of Vue and when I have something to share about this issue I'll come back.
Thanks!

**Comment by ebebbington** [comment]
Sure no problem! You can join the discord (https://discord.gg/CpxheK) and ask as many questions as you want, we can also mark your PR for hacktoberfest if you would like

The logic i referenced above (`if (to.path === ...)`) is at `./src/public/js/_app.js:148`

That's why we don't check if the user is authed, but users should be allowed to visit the home page (`/`) when not logged in, but i think we might. need to make a case. for if it's the home page, set the user in vue store if they are authenticated.

**Comment by tiagostutz** [comment]
Thanks! I'll work on it this "opensource friday".

**Comment by tiagostutz** [comment]
I updated my branch, but I'm struggling to run on MacOS:

```bash
realworld_drash | ERROR in ./vue/routes/ArticleEdit.vue?vue&type=style&index=0&lang=scss& (./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./vue/routes/ArticleEdit.vue?vue&type=style&index=0&lang=scss&)
realworld_drash | Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
realworld_drash | Error: Missing binding /var/www/src/node_modules/node-sass/vendor/linux-x64-64/binding.node
realworld_drash | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x
realworld_drash | 
realworld_drash | Found bindings for the following environments:
realworld_drash |   - OS X 64-bit with Node.js 10.x
realworld_drash | 
realworld_drash | This usually happens because your environment has changed since running `npm install`.
realworld_drash | Run `npm rebuild node-sass` to download the binding for your current environment.
realworld_drash |     at module.exports (/var/www/src/node_modules/node-sass/lib/binding.js:15:13)
```

I tried to run the `npm rebuild node-sass`, but it didn't work. I tried to use another version of node, but without success too.

Anyone had this problem, also?

**Comment by crookse** [comment]
@tiagostutz, that's very strange. when i run the application, everything works fine for me and im on a mac. do you have a branch up that i can fork to further debug?

also, @ebebbington, we should probably upgrade the container's node version. i've seen this issue many times with node 10. not sure why it's working on my system and not @tiagostutz's though.

**Comment by tiagostutz** [comment]
Yeah, I also saw this issue with node 10 many times. I tried to upgrade it with no success, tough.

I'm working on my master branch, but I'll try to run the master of this repo first and, if I still struggle, I'll come back to give mor details. Thanks!

**Comment by tiagostutz** [comment]
I just tested with `master` of this repo and the same problem occurs. If you could test with a clean run @crookse I'd appreciate. 
Meanwhile I'll keep trying too.


Thanks.!

**Comment by ebebbington** [comment]
I’ve got a Mac too so I can try see if I get the same error

**Comment by ebebbington** [comment]
I did:

```
$ rm -rf deno-drash-realworld-exampl-app
$ git clone ...
$ cd deno-drash-realworld-example-app
$ docker-compose up
```

No errors for me - @tiagostutz did you install the npm dependencies manually? Maybe try `rm -rf src/node_modules` then `$ docker exec ddrash_server npm i`?

**Comment by tiagostutz** [comment]
Thanks guys! 
I could make it work here by removing my **latest** debian image and the drash image itself (`docker rmi` ).
Now, back to work.

**Comment by ebebbington** [comment]
Sweet! :D

**Comment by tiagostutz** [comment]
:D

Just a question, this dev setup does not have hot reload enabled, correct? Is there any other setup with hot reload or is this an issue for the future?

**Comment by ebebbington** [comment]
You're correct, this is added in #108 but for the time being, you can just add `--watch` to the command for `realworld_drash` inside `docker-compose.yml`, and update the deno version in `.docker/drash.dockerfile` to `v1.5.4` :)

**Comment by tiagostutz** [comment]
> You're correct, this is added in #108 but for the time being, you can just add --watch to the command for realworld_drash inside docker-compose.yml, and update the deno version in .docker/drash.dockerfile to v1.5.4 :)

Nice... I'm giving it a try here, but it didn't work when changing a .vue file. I think we need the `--watch` on the webpack executable, but if we do it in the script it "hangs" the execution I think.
Am I missing something here? If not, I'll work on a development environment with `--watch` in the webpack and deno commands.

**Comment by ebebbington** [comment]
ohhh my bad i thought you meant for the deno server 😬 seems we do have one: `npm run webpack-watch` - try this:

```
$ docker-compose up -d # start the env etc etc
$ docker exec realworld_drash npm run webpack-watch
```

That way, the server can still run, and you can watch the vue files (both being in different shells)

**Comment by tiagostutz** [comment]
Nice! 
I have implemented a suggestion to make the `docker-compose up` bring the deno server and the webpack-watch execution together without needing separed commands. What do you think:

https://github.com/tiagostutz/deno-drash-realworld-example-app/blob/issue-90/.docker/drash.dockerfile

This way, we just need the `docker-compose up` command and the deno server and webpack starts with hot reload enabled.

**Comment by ebebbington** [comment]
> Nice!
> I have implemented a suggestion to make the `docker-compose up` bring the deno server and the webpack-watch execution together without needing separed commands. What do you think:
> 
> https://github.com/tiagostutz/deno-drash-realworld-example-app/blob/issue-90/.docker/drash.dockerfile
> 
> This way, we just need the `docker-compose up` command and the deno server and webpack starts with hot reload enabled.

We'll discuss this in the PR now one has been opened :)
